on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Always runs
        uses: actions/checkout@v3

      - name: Runs for schedule
        if: ${{ github.event_name == 'schedule' }}
        run: echo "hello from schedule"
      
      - name: Runs for push
        if: ${{ github.event_name == 'push' }}
        run: echo "hello from push"
