name: Build Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_GCR_KEY }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-actions@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: gcr.io/project_id/<image_name>:<tag> # csv list registry/image_name:tag,registry/image_name:tag
